name: template-test
description: Describe your template explaining its purpose
types:
  - app-template
inputs:
  - label: Project name
    type: text
    name: project_name
    default: project-name
  - label: Project folder
    type: text
    name: project_folder
    default: folder-name
    pattern: '[a-zA-Z0-9](\w|-)*$'
